"""fig_3_b_elasticity.py

Computes repeat-number elasticity for all birds and produces three figures:

  repeat_number_elasticity_all_birds.png
    — histogram of elasticity values across all birds, with median line
      and Wilcoxon signed-rank test vs 0 (Fig 3B)

  elasticity_pair_scatter_adjacent_rho.png  (also saved as figures/Supplementary/Supp_2/supp_2_a.png)
    — scatter of elasticity pairs for adjacent syllables coloured by
      Spearman ρ (significant pairs only, n ≥ 100)

  elasticity_pair_scatter_next_rho.png  (also saved as figures/Supplementary/Supp_2/supp_2_b.png)
    — same for next-syllable pairs

All figures saved to figures/Figure 3/.

Prerequisites:
  output/Adjacent Correlations/Adjacent_Correlations_correction_bh.csv
  output/Next Correlations/Next_Correlations_correction_bh.csv
  (generated by plot_fig_2_c.py)
"""

import os

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import yaml
from matplotlib.ticker import AutoMinorLocator, MultipleLocator, FuncFormatter
from scipy import stats

from elasticity import build_repeat_df, calculate_repeat_number_elasticity
from get_compressed_syntax import load_and_process_data
from get_repeat_data import REPO_ROOT, syllables_mapping

# --- Paths ---
yaml_path = os.path.join(REPO_ROOT, "yamls", "bird_1.yaml")
with open(yaml_path, "r") as f:
    config = yaml.safe_load(f)

output_folder = os.path.join(REPO_ROOT, "figures", "Figure 3")
os.makedirs(output_folder, exist_ok=True)

adj_file  = os.path.join(REPO_ROOT, config["adjacent_corr_combined_path"])
next_file = os.path.join(REPO_ROOT, config["next_corr_combined_path"])

bird_nums = list(syllables_mapping.keys())  # ['1','2','3','4','5','6']

# ══════════════════════════════════════════════════════════════════════════════
# 1. Compute elasticity for all birds (in memory — no CSVs)
# ══════════════════════════════════════════════════════════════════════════════

all_data = []

for bird_num in bird_nums:
    df = load_and_process_data(bird_num)
    repeat_df = build_repeat_df(df)
    repeat_df = repeat_df[repeat_df['syl'].isin(syllables_mapping[bird_num])]
    elasticity_df = calculate_repeat_number_elasticity(repeat_df)
    elasticity_df['bird_num'] = int(bird_num)
    all_data.append(elasticity_df)

combined_df = pd.concat(all_data, ignore_index=True)
elasticities = combined_df['elasticity'].values

# Print summary
print(f"\n{'='*50}")
print("DATA POINTS PER BIRD:")
print(f"{'='*50}")
for bird_num in bird_nums:
    count = len(combined_df[combined_df['bird_num'] == int(bird_num)])
    print(f"  Bird {bird_num}: {count} data points")
print(f"\n  Total across all birds: {len(elasticities)} data points")
print(f"\n  Range of elasticity values: [{np.min(elasticities):.4f}, {np.max(elasticities):.4f}]")
print(f"{'='*50}\n")

# ══════════════════════════════════════════════════════════════════════════════
# 2. Histogram: all-birds elasticity (Fig 3B)
# ══════════════════════════════════════════════════════════════════════════════

import seaborn as sns

plt.rcParams.update({
    "font.size": 10,
    "axes.labelsize": 11,
    "axes.titlesize": 11,
    "xtick.labelsize": 11,
    "ytick.labelsize": 11,
    "legend.fontsize": 10
})

plt.figure(figsize=(2.8, 2.2))
sns.histplot(elasticities, bins=5, kde=False, color='steelblue', edgecolor='black')

median_val = np.median(elasticities)
plt.axvline(median_val, color='red', linestyle='-', linewidth=2, label="")

plt.xlabel("Repeat number elasticity", fontsize=11)
plt.ylabel("Frequency", fontsize=11)
plt.title("")
plt.xlim(-1, 1)
plt.ylim(0, 10)
plt.gca().xaxis.set_major_locator(MultipleLocator(0.5))
plt.gca().yaxis.set_major_locator(MultipleLocator(2))
plt.gca().xaxis.set_minor_locator(AutoMinorLocator(2))
plt.gca().tick_params(axis='both', which='major', width=1, length=6, labelsize=11)
plt.gca().tick_params(axis='both', which='minor', width=0.5, length=4, labelsize=11)
plt.tight_layout()

plt.savefig(os.path.join(output_folder, "repeat_number_elasticity_all_birds.png"), dpi=300, bbox_inches="tight")
plt.savefig(os.path.join(output_folder, "repeat_number_elasticity_all_birds.svg"), bbox_inches="tight")
plt.show()
print(f"Saved: repeat_number_elasticity_all_birds.png")

# Wilcoxon test
elasticities_no_zero = elasticities[elasticities != 0]
if len(elasticities_no_zero) < 5:
    print("Too few non-zero values for Wilcoxon test.")
else:
    w_stat, p_val = stats.wilcoxon(elasticities_no_zero, alternative='two-sided')
    print(f"Median elasticity: {median_val:.4f}")
    print(f"Wilcoxon signed-rank test vs 0:")
    print(f"  W = {w_stat:.3f}, p = {p_val:.3e}")


# ══════════════════════════════════════════════════════════════════════════════
# Helper: scatter plot of elasticity pairs coloured by rho
# ══════════════════════════════════════════════════════════════════════════════

def _elasticity_scatter(corr_df, combined_df, title, fname_stem, seed, supp_path=None):
    corr_df = corr_df.dropna(subset=['rho'])
    corr_df = corr_df.merge(
        combined_df[['bird_num', 'syl', 'elasticity']],
        left_on=['bird_num', 'syl1'], right_on=['bird_num', 'syl'], how='left'
    ).rename(columns={'elasticity': 'elasticity_1'}).drop(columns='syl')
    corr_df = corr_df.merge(
        combined_df[['bird_num', 'syl', 'elasticity']],
        left_on=['bird_num', 'syl2'], right_on=['bird_num', 'syl'], how='left'
    ).rename(columns={'elasticity': 'elasticity_2'}).drop(columns='syl')
    corr_df = corr_df.dropna(subset=['elasticity_1', 'elasticity_2'])
    corr_df = corr_df[
        (corr_df['sample_size'] >= 100) &
        (corr_df['new_significance_status'] == 'significant')
    ]
    corr_df['elasticity_product'] = corr_df['elasticity_1'] * corr_df['elasticity_2']
    corr_df['elasticity_sign_relation'] = np.where(
        corr_df['elasticity_product'] > 0, 'Same elasticity sign', 'Different elasticity sign'
    )

    no_diag = corr_df[corr_df['elasticity_1'] != corr_df['elasticity_2']].copy()

    plt.figure(figsize=(2.2, 1.9))
    np.random.seed(seed)
    jitter = 0.01
    x_j = no_diag['elasticity_1'] + np.random.uniform(-jitter, jitter, len(no_diag))
    y_j = no_diag['elasticity_2'] + np.random.uniform(-jitter, jitter, len(no_diag))
    pos_mask = no_diag['rho'] > 0
    neg_mask = no_diag['rho'] < 0

    sc_pos = plt.scatter(x_j[pos_mask], y_j[pos_mask],
                         c=no_diag.loc[pos_mask, 'rho'], s=25, cmap='coolwarm',
                         edgecolor='k', alpha=0.8, marker='^', vmin=-1, vmax=1)
    plt.scatter(x_j[neg_mask], y_j[neg_mask],
                c=no_diag.loc[neg_mask, 'rho'], s=25, cmap='coolwarm',
                edgecolor='k', alpha=0.8, marker='o', vmin=-1, vmax=1)

    plt.axhline(0, color='gray', linestyle='--', linewidth=1)
    plt.axvline(0, color='gray', linestyle='--', linewidth=1)
    plt.xlim(-0.5, 0.5)
    plt.ylim(-0.5, 0.5)
    plt.xlabel("Elasticity Phrase 1", fontsize=10)
    plt.ylabel("Elasticity Phrase 2", fontsize=10)
    plt.title(title, fontsize=10)

    cbar = plt.colorbar(sc_pos, shrink=0.8)
    cbar.set_label("Correlation", fontsize=10)
    cbar.set_ticks([-1, 0, 1])
    cbar.set_ticklabels(["-1", "0", "+1"])

    _sparse = FuncFormatter(lambda x, pos: '' if abs(abs(x) - 0.25) < 1e-9 else f'{x:g}')
    plt.gca().xaxis.set_major_locator(MultipleLocator(0.25))
    plt.gca().yaxis.set_major_locator(MultipleLocator(0.25))
    plt.gca().xaxis.set_major_formatter(_sparse)
    plt.gca().yaxis.set_major_formatter(_sparse)

    # Quadrant counts
    def _qcount(df, x_sign, y_sign, rho_sign):
        return ((np.sign(df['elasticity_1']) == x_sign) &
                (np.sign(df['elasticity_2']) == y_sign) &
                (np.sign(df['rho']) == rho_sign) &
                (df['elasticity_1'] != df['elasticity_2'])).sum()

    for (x_pos_txt, y_pos_txt, xs, ys) in [(0.35, 0.35, 1, 1), (-0.35, 0.35, -1, 1),
                                             (-0.35, -0.25, -1, -1), (0.35, -0.25, 1, -1)]:
        n_pos = _qcount(corr_df, xs, ys, 1)
        n_neg = _qcount(corr_df, xs, ys, -1)
        plt.text(x_pos_txt, y_pos_txt, f"{n_pos}", color='#B2182B', fontsize=10,
                 fontweight='bold', ha='center', va='center', transform=plt.gca().transData)
        plt.text(x_pos_txt, y_pos_txt - 0.10, f"{n_neg}", color='#2166AC', fontsize=10,
                 fontweight='bold', ha='center', va='center', transform=plt.gca().transData)

    # Debug: quadrant raw data
    print(f"\n{'='*60}")
    print(f"{title.upper()} - RAW DATA BY QUADRANT (excluding self-comparisons)")
    print(f"{'='*60}")
    for label, mask in [("Q1 (x>0, y>0)", (no_diag['elasticity_1'] > 0) & (no_diag['elasticity_2'] > 0)),
                        ("Q2 (x<0, y>0)", (no_diag['elasticity_1'] < 0) & (no_diag['elasticity_2'] > 0)),
                        ("Q3 (x<0, y<0)", (no_diag['elasticity_1'] < 0) & (no_diag['elasticity_2'] < 0)),
                        ("Q4 (x>0, y<0)", (no_diag['elasticity_1'] > 0) & (no_diag['elasticity_2'] < 0))]:
        d = no_diag[mask]
        print(f"\n{label}: {len(d)} points")
        print(d[['bird_num', 'syl1', 'syl2', 'elasticity_1', 'elasticity_2', 'rho']].to_string())
    print("="*60 + "\n")

    plt.tight_layout()
    if supp_path:
        os.makedirs(os.path.dirname(supp_path), exist_ok=True)
        plt.savefig(supp_path, dpi=300, bbox_inches="tight")
        plt.savefig(supp_path.replace('.png', '.svg'), bbox_inches="tight")
        print(f"Saved: {supp_path}")
    plt.show()


# ══════════════════════════════════════════════════════════════════════════════
# 3. Adjacent correlation scatter
# ══════════════════════════════════════════════════════════════════════════════

adj_df = pd.read_csv(adj_file)
_elasticity_scatter(adj_df, combined_df,
                    title="Phrase 1 \u2192 Phrase 2\nAdjacent",
                    fname_stem="elasticity_pair_scatter_adjacent_rho",
                    seed=42,
                    supp_path=os.path.join(REPO_ROOT, "figures", "Supplementary", "Supp_2", "supp_2_a.png"))

# ══════════════════════════════════════════════════════════════════════════════
# 4. Next correlation scatter
# ══════════════════════════════════════════════════════════════════════════════

next_df = pd.read_csv(next_file)
_elasticity_scatter(next_df, combined_df,
                    title="Phrase 1 \u2192 Phrase 2\nNext",
                    fname_stem="elasticity_pair_scatter_next_rho",
                    seed=43,
                    supp_path=os.path.join(REPO_ROOT, "figures", "Supplementary", "Supp_2", "supp_2_b.png"))

# Print syllables per bird
print("\nSyllables analyzed per bird:")
for bird_num in bird_nums:
    sylls = combined_df[combined_df['bird_num'] == int(bird_num)]['syl'].unique()
    print(f"  Bird {bird_num}: {', '.join(map(str, sylls))}")
